title:             Clean Blog
email:             victor@dacker.co
description:       A blog for political reviews
author:            Victor Challier & Anatole Flahault
baseurl:           "/"
url:               "http://blackrockdigital.github.io"

# Social Profiles
twitter_username:  victor_challier
github_username:   vchallier

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
