title:             La macronie
email:             victor@dacker.co
description:       Notes sur la politique française, façon "des chiffres et des lettres"
author:            Victor Challier & Anatole Flahault
baseurl:           "/blog-jekyll/"
url:               "https://vchallier.github.io"

# Social Profiles
twitter_username:  victor_challier
github_username:   vchallier

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
